# Generated by Django 3.2.4 on 2021-06-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('air_conditioner', '0003_remove_detailmodel_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='aim',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='log',
            name='speed',
            field=models.FloatField(default=0),
        ),
    ]
